### ISSUE TITLE
Shrines in Greengarden

### ISSUE THREAD

**Issue by Bagoffelt** [amia-team/amia#12]
3 Shrines

> Lathander - in Fey Lake

> Hoar - in Greengarden

> Kelemvor/Jergal - in Fey Lake West

All three are in construction phase, and have been put up to test

**Comment by cltalmadge** [comment]
@Bagoffelt Feel free to change the priority here if you disagree. This was just me taking a crack at guessing how important it is to get into an update soon. Haha
