### ISSUE TITLE
Settlement Guards: Moonpier

### ISSUE THREAD

**Issue by Jesacondrey** [amia-team/amia#59]
Add Settlement Guards to Moonpier.

1. Add guards to the palette: Elite, Standard, Scout, Mage, Construct. (DONE)
2. Add guards to the core Settlement Guards area with Henchman scripts. (DONE)
3. Replace guards in Moonpier areas with new templates from palette. (DONE)

**Comment by Bagoffelt** [comment]
Yay Jes!

**Comment by Bagoffelt** [comment]
Can cross it off :)
