### ISSUE TITLE
Settlement Guards: Crouching Lemur

### ISSUE THREAD

**Issue by Jesacondrey** [amia-team/amia#60]
Add Settlement Guards to Crouching Lemur Monastery.

1. Add guards to the palette: Elite, Standard, Scout, Mage. (DONE)
2. Add guards to the core Settlement Guards area with Henchman scripts. (DONE)
3. Replace guards in Crouching Lemur areas with new templates from palette. (DONE)

**Comment by Bagoffelt** [comment]
And another one bites the dust.
